// SPDX-License-Identifier: MIT
//============================================================================
//  pll_top_rnm.sv  --  REAL-NUMBER (AMS / mixed-signal) MODEL
//----------------------------------------------------------------------------
//  Real-number model of the dual-control-path ring-oscillator PLL top cell.
//  The analog control path is modelled with SystemVerilog `real`:
//
//     REFCLK,PLL_CLK --> PFD (phase/freq detector, sign of phase error)
//                    --> charge pump (I_CP)             [current, real]
//                    --> passive loop filter, R1/C1/C2  [discrete real integ.]
//                          -> V_FINE   (fine, low-gain path)
//                          -> V_C1     (sensed by gm-C)
//                    --> gm-C coarse integrator, forces V_C1 -> V_REF
//                          -> V_COARSE (coarse, high-gain path)
//     dual-control VCO:  f = f0 + K_FINE*(V_FINE-V0) + K_COARSE*(V_COARSE-V0)
//                                                       [real -> frequency]
//     PLL_CLK is generated by a phase accumulator clocked at that frequency,
//     so the output frequency evolves CONTINUOUSLY with the control voltages.
//
//  This reproduces the paper's loop math (Williams et al., CICC 2004,
//  SPECS Table I) as a leap-frog discrete-time integration of the loop
//  filter and the gm-C stage, updated on every REFCLK edge (the natural
//  loop-update rate of a PFD/CP PLL).
//
//  Internal analog nodes V_FINE / V_COARSE / V_C1 and the VCO frequency are
//  exposed as `real` outputs for probing (V_CTRL / V_VCO in the port list).
//
//  Pure SV `real` -- no proprietary wreal / nettype-real libraries, so it
//  compiles with common tools (iverilog -g2012, Verilator 5.x).
//
//  Same top port list & the same headline parameters as the pre/post-layout
//  models, so it is interchangeable in the testbench.
//============================================================================
`ifndef PLL_TOP_RNM_SV
`define PLL_TOP_RNM_SV
`timescale 1ps/1ps

module pll_top #(
    parameter integer M          = 10,
    parameter real    F_REF_HZ   = 27.0e6,
    parameter real    JITTER_PS  = 0.0,          // RNM is deterministic by default
    parameter real    LOCK_TAU_S = 177.0e-9,     // (informational, for reports)
    parameter real    SETTLE_S   = 1.5e-6,
    parameter real    FREERUN_HZ = 120.0e6,      // used to seed V_FINE at enable
    parameter real    OVERSHOOT_HZ = 500.0e6,    // (informational)
    parameter integer SEED       = 32'h1234ABCD,
    parameter [255:0] CORNER     = "TT",
    // ---- analog / loop parameters (paper Table I values by default) ----
    parameter real    I_CP_A     = 193.0e-6,     // charge-pump current   [A]
    parameter real    R1_OHM     = 22.4e3,       // loop-filter series R   [ohm]
    parameter real    C1_F       = 51.2e-12,     // loop-filter main C     [F]
    parameter real    C2_F       = 1.6e-12,      // loop-filter high-freq cap C2 [F]
    parameter real    GM_S       = 0.582e-6,     // gm-C transconductance  [S]
    parameter real    GOUT_S     = 5.8e-6,       // gm-C output conductance[S]
    parameter real    C3_F       = 150.0e-12,    // gm-C integrating C     [F]
    parameter real    K_FINE_HZV = 15.0e6,       // K_VCOFINE   [Hz/V]
    parameter real    K_COARSE_HZV = 866.0e6,    // K_VCOCOARSE [Hz/V]
    parameter real    V_REF_V    = 0.60,         // gm-C reference (varactor knee)
    parameter real    V0_FINE_V  = 0.60,         // fine-path operating point
    parameter real    V0_COARSE_V= 0.90,         // coarse-path operating point
    parameter real    F0_HZ      = 270.0e6       // VCO freq at (V_FINE=V0_FINE,
                                                 //              V_COARSE=V0_COARSE)
)(
    input  wire  REFCLK,
    output reg   PLL_CLK,
    input  wire  PG,
    inout  wire  VDD,
    inout  wire  VSS,
    input  wire  VFINE,
    input  wire  V_REF,
    input  wire  VREF,
    input  wire  VREG_REF,
    input  wire  IBCP,
    input  wire  IBREG,
    input  wire  IB,
    // ---- observability ----
    output reg          LOCKED,
    output real         F_VCO_HZ,   // instantaneous VCO frequency  [Hz]
    // ---- exposed analog control-path reals (V_CTRL / V_VCO probes) ----
    output real         V_CTRL,     // = V_FINE node (dominant fine control)   [V]
    output real         V_VCO,      // = V_COARSE node (coarse control)        [V]
    output real         V_C1_NODE   // = voltage on C1 (sensed by gm-C)        [V]
);

    localparam real F_TARGET_HZ = M * F_REF_HZ;
    localparam real SEC_PER_PS  = 1.0e-12;
    localparam real TWO_PI      = 6.28318530718;

    // ------------------------------------------------------------------
    // Analog state (all `real`)
    //   v_fine  : loop-filter output node = charge-pump output (fine control)
    //   v_c1    : voltage on C1 (node between R1 and C1), sensed by gm-C
    //   v_coarse: gm-C integrator output (coarse control)
    // ------------------------------------------------------------------
    real v_fine, v_c1, v_coarse;
    real f_vco;                 // instantaneous VCO frequency
    real t_prev_ref;            // last REF edge time  [s]
    real t_enable;              // enable time         [s]

    // PFD state (tri-state phase/frequency detector)
    reg     pfd_up, pfd_dn;     // 1-bit UP/DN flags
    real    t_ref_edge;         // timestamp of the pending REF rising edge [s]
    real    t_fb_edge;          // timestamp of the pending FB  rising edge [s]

    function real now_s; now_s = $realtime * SEC_PER_PS; endfunction

    // dual-path VCO transfer function: frequency from the two control voltages
    function real vco_freq(input real vf, input real vc);
        real f;
        f = F0_HZ + K_FINE_HZV*(vf - V0_FINE_V)
                  + K_COARSE_HZV*(vc - V0_COARSE_V);
        if (f < 5.0e6)  f = 5.0e6;      // clamp to a sane tuning range
        if (f > 800.0e6) f = 800.0e6;
        vco_freq = f;
    endfunction

    // invert the VCO map to seed v_fine so the ring free-runs at FREERUN_HZ
    // when enabled (with v_coarse parked at its operating point).
    function real seed_vfine(input real f_target);
        seed_vfine = V0_FINE_V + (f_target - F0_HZ - 0.0)/K_FINE_HZV;
    endfunction

    // ------------------------------------------------------------------
    // Init
    // ------------------------------------------------------------------
    initial begin
        PLL_CLK    = 1'b0;
        LOCKED     = 1'b0;
        v_fine     = V0_FINE_V;
        v_c1       = V_REF_V;
        v_coarse   = V0_COARSE_V;
        f_vco      = F0_HZ;
        F_VCO_HZ   = F0_HZ;
        V_CTRL     = V0_FINE_V;
        V_VCO      = V0_COARSE_V;
        V_C1_NODE  = V_REF_V;
        t_prev_ref = 0.0;
        t_enable   = 0.0;
        pfd_up     = 0;
        pfd_dn     = 0;
        t_ref_edge = 0.0;
        t_fb_edge  = 0.0;
    end

    // ------------------------------------------------------------------
    // Tri-state PFD: compare REFCLK vs the divided-down feedback clock fbclk.
    //   * A REF rising edge with no FB pending -> UP asserts, timestamp saved.
    //   * A FB rising edge with no REF pending -> DN asserts, timestamp saved.
    //   * When the trailing edge arrives, the signed phase error (in seconds)
    //     is latched (phase_err_s) and both flags reset -- exactly the CP
    //     on-time.  Positive phase_err_s = REF leads FB = pump UP = raise freq.
    // gates on PG level (no racing "running" flag).
    // ------------------------------------------------------------------
    reg  fbclk;                 // feedback (divided) clock
    real phase_err_s;           // latched signed phase error this cycle  [s]
    reg  err_valid;             // a fresh phase_err_s is available

    always @(posedge REFCLK) begin
        if (PG === 1'b1) begin
            if (pfd_dn) begin
                // FB already came first -> REF is the trailing edge.
                // FB led REF by (now - t_fb_edge): phase error is NEGATIVE.
                phase_err_s = -(now_s() - t_fb_edge);
                err_valid   = 1'b1;
                pfd_dn = 0; pfd_up = 0;
            end else begin
                pfd_up     = 1;
                t_ref_edge = now_s();
            end
        end
    end
    always @(posedge fbclk) begin
        if (PG === 1'b1) begin
            if (pfd_up) begin
                // REF already came first -> FB is the trailing edge.
                // REF led FB by (now - t_ref_edge): phase error is POSITIVE.
                phase_err_s = (now_s() - t_ref_edge);
                err_valid   = 1'b1;
                pfd_up = 0; pfd_dn = 0;
            end else begin
                pfd_dn    = 1;
                t_fb_edge = now_s();
            end
        end
    end

    // ------------------------------------------------------------------
    // PG enable
    // ------------------------------------------------------------------
    always @(posedge PG) begin
        t_enable   = now_s();
        t_prev_ref = now_s();
        // seed the fine node so the ring starts near FREERUN_HZ (coarse parked)
        v_fine     = seed_vfine(FREERUN_HZ);
        v_c1       = v_fine;         // C1 starts at the CP output level
        v_coarse   = V0_COARSE_V;
        pfd_up     = 0;
        pfd_dn     = 0;
        err_valid  = 1'b0;
        phase_err_s= 0.0;
    end
    always @(negedge PG) begin
        LOCKED   = 1'b0;
        PLL_CLK  = 1'b0;
    end

    // ------------------------------------------------------------------
    // LOOP UPDATE  (discrete-time real integration).
    // Runs on every REFCLK rising edge -- the PFD/CP update rate.
    //
    //   dt          : elapsed time since last update  (= ref period)
    //   phase error : approximated from the PFD UP/DN accumulators, scaled to
    //                 the fraction of a cycle the CP was on.
    //   i_cp        : charge-pump current pushed/pulled onto the loop filter.
    //
    //   Loop-filter (R1 || C1, with C2) discrete update:
    //     The CP injects charge q = i_cp*dt onto the (C1+C2) node.
    //       v_fine  = v_c1 + i_cp*R1        (instantaneous R1 drop)
    //       dv_c1   = i_cp*dt / (C1 + C2)   (integrated onto the caps)
    //
    //   gm-C coarse integrator (forces v_c1 -> V_REF):
    //       i_gm    = gm*(v_c1 - V_REF)
    //       dv_coarse = (i_gm - gout*(v_coarse - V0)) * dt / C3
    //     DC: v_coarse settles so the coarse path absorbs the low-freq error,
    //     pinning v_c1 to V_REF (paper section IV-B).
    // ------------------------------------------------------------------
    // The loop updates once per REF cycle, driven by a fresh latched phase
    // error from the tri-state PFD (err_valid).  Charge pumped this cycle:
    //   q_cp = I_CP * phase_err_s   (current x on-time; signed).
    // That charge lands on the loop-filter caps and is integrated.  dt is the
    // ref period (the interval this error accrued over).
    always @(posedge REFCLK) begin
        if ((PG === 1'b1) && err_valid) begin
            real dt, q_cp, i_cp_avg, dv_c1, i_gm, dv_coarse;
            err_valid = 1'b0;
            dt = now_s() - t_prev_ref;
            t_prev_ref = now_s();
            if (dt <= 0.0) dt = 1.0/(F_REF_HZ);

            // charge pumped and its cycle-average current
            q_cp     = I_CP_A * phase_err_s;      // [Coulomb], signed
            i_cp_avg = q_cp / dt;                 // avg CP current this cycle

            // --- loop filter: charge integrates onto (C1 + C2) ---
            dv_c1 = q_cp / (C1_F + C2_F);
            v_c1  = v_c1 + dv_c1;
            // fine (CP output) node = cap voltage + R1 drop (adds the loop zero)
            v_fine = v_c1 + i_cp_avg * R1_OHM;

            // --- gm-C coarse integrator: centres v_c1 -> V_REF ---
            i_gm      = GM_S * (v_c1 - V_REF_V);
            dv_coarse = (i_gm - GOUT_S*(v_coarse - V0_COARSE_V)) * dt / C3_F;
            v_coarse  = v_coarse + dv_coarse;

            // clamp control voltages to the 1.8 V rail
            if (v_fine   < 0.0) v_fine   = 0.0;  if (v_fine   > 1.8) v_fine   = 1.8;
            if (v_c1     < 0.0) v_c1     = 0.0;  if (v_c1     > 1.8) v_c1     = 1.8;
            if (v_coarse < 0.0) v_coarse = 0.0;  if (v_coarse > 1.8) v_coarse = 1.8;

            // --- update VCO frequency from both control voltages ---
            f_vco    = vco_freq(v_fine, v_coarse);

            // publish probes
            F_VCO_HZ  = f_vco;
            V_CTRL    = v_fine;
            V_VCO     = v_coarse;
            V_C1_NODE = v_c1;
        end
    end

    // ------------------------------------------------------------------
    // VCO / phase accumulator: generate PLL_CLK (and the /M feedback clock)
    // by toggling every half period at the current f_vco.  Because f_vco is
    // recomputed continuously from the control voltages, the output frequency
    // tracks the loop transient exactly.
    // ------------------------------------------------------------------
    integer div_cnt;
    // deterministic optional jitter (off by default in the RNM)
    integer rng_state; initial rng_state = SEED;
    function real urand01;
        rng_state = (rng_state*1103515245 + 12345) & 32'h7fffffff;
        urand01   = (rng_state + 1.0)/2147483649.0;
    endfunction
    function real gauss; real u1,u2; u1=urand01(); u2=urand01();
        gauss = $sqrt(-2.0*$ln(u1))*$cos(TWO_PI*u2); endfunction

    initial begin fbclk = 1'b0; div_cnt = 0; end

    real hp_ps, jit_ps;
    always begin
        if (PG === 1'b1) begin
            hp_ps = (1.0/f_vco)/SEC_PER_PS/2.0;
            jit_ps = (JITTER_PS > 0.0) ? (JITTER_PS/1.41421356237*gauss()) : 0.0;
            hp_ps = hp_ps + jit_ps;
            if (hp_ps < 1.0) hp_ps = 1.0;
            #(hp_ps) PLL_CLK = ~PLL_CLK;
            // build the /M feedback clock: rising edge every M VCO periods.
            // toggle fbclk twice per M-count so it is a proper clock at f/M.
            if (PLL_CLK == 1'b1) begin           // count VCO rising edges
                div_cnt = div_cnt + 1;
                if (div_cnt >= (M/2 > 0 ? M/2 : 1)) begin
                    div_cnt = 0;
                    fbclk   = ~fbclk;            // half of the /M period
                end
            end
        end else begin
            PLL_CLK = 1'b0;
            fbclk   = 1'b0;
            div_cnt = 0;
            @(posedge PG);
        end
    end

    // ------------------------------------------------------------------
    // Lock detector: locked when past SETTLE_S and within +/-1% of target.
    // ------------------------------------------------------------------
    real ferr_lock;
    always @(posedge REFCLK) begin
        if (PG === 1'b1) begin
            ferr_lock = (f_vco - F_TARGET_HZ)/F_TARGET_HZ;
            if (ferr_lock < 0.0) ferr_lock = -ferr_lock;
            if (!LOCKED) begin
                if (((now_s()-t_enable) >= SETTLE_S) && (ferr_lock <= 0.01))
                    LOCKED <= 1'b1;
            end else begin
                if (ferr_lock > 0.02) LOCKED <= 1'b0;
            end
        end
    end

`ifdef PLL_DEBUG
    initial $display("[rnm] K_FINE=%0.1f MHz/V K_COARSE=%0.1f MHz/V I_CP=%0.1f uA -> F_TARGET=%0.3f MHz",
                     K_FINE_HZV/1e6, K_COARSE_HZV/1e6, I_CP_A*1e6, F_TARGET_HZ/1e6);
`endif

endmodule
`endif
